### ISSUE TITLE
Unauthorized Token - This token has not been authorized

### ISSUE THREAD

**Issue by Ryrynz** [marc2k3/foo_lastfm_playcount_sync#1]
This error is given by foobar before I have a chance to authorize in the browser.
The button still says authorize after authorization has been given and persists after a restart of Foobar. Perhaps you could "borrow" foo_scrobble's authorization code? It works a lot better.

**Comment by marc2k3** [comment]
The token only gets submitted when you click OK here: 

![image](https://user-images.githubusercontent.com/34617027/69327054-ce7f9a80-0c44-11ea-9a96-6e8b95ddbedb.png)

It's not my fault you can't read.

**Comment by Ryrynz** [comment]
Generally the last thing someone does is actually read a window that prompts within a second of clicking authorize..  Also the sentence is not very good and is easily construed as you have granted permission successfully, click OK to continue. This isn't how I would word a dialogue box in this situation. This window should instead say, that a browser has opened a window to allow authorization. Also one would expect this browser window to open in the foreground which it does not.

**Comment by Ryrynz** [comment]
Would recommend doing what Foo_scrobble does in this instance and have the button change from authorize to complete rather than popping up a window breaking the serial nature of this operation. It's just not good from a design perspective.

**Comment by marc2k3** [comment]
> Generally the last thing someone does is actually read a window that prompts within a second of clicking authorize.

You utter fuckwit.
